'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Authentication.ActiveDirectory

    Partial Public Class Settings

        '''<summary>
        '''pnlError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Image1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tblSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''MessageCell control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MessageCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''plAuthentication control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAuthentication As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkAuthentication control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAuthentication As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHidden control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHidden As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHidden control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHidden As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plSynchronizeRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSynchronizeRole As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkSynchronizeRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSynchronizeRole As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowSynchornizePassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowSynchornizePassword As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plSynchornizePassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSynchornizePassword As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkSynchronizePassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSynchronizePassword As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowAutoCreate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowAutoCreate As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plAutoCreate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAutoCreate As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkAutoCreate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAutoCreate As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plStripDomainName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStripDomainName As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkStripDomainName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkStripDomainName As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plProvider control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plProvider As Global.System.Web.UI.UserControl

        '''<summary>
        '''cboProviders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboProviders As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plAuthenticationType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAuthenticationType As Global.System.Web.UI.UserControl

        '''<summary>
        '''cboAuthenticationType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboAuthenticationType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rowRootDomain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowRootDomain As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plRootDomain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRootDomain As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtRootDomain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRootDomain As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rowUserName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowUserName As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plUserName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUserName As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtUserName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUserName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rowPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowPassword As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPassword As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rowConfirm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowConfirm As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plConfirm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plConfirm As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtConfirm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtConfirm As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valConfirm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valConfirm As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''rowEmailDomain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowEmailDomain As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plEmailDomain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailDomain As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtEmailDomain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailDomain As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rowDefaultDomain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowDefaultDomain As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plDefaultDomain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDefaultDomain As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtDefaultDomain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDefaultDomain As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rowSubNet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowSubNet As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plAutoIP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAutoIP As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtAutoIP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAutoIP As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rowBots control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowBots As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plBots control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plBots As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtBots control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBots As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
