'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace DotNetNuke.Authentication.ActiveDirectory

    '''<summary>
    '''WindowsSignin class.
    '''</summary>
    '''<remarks>
    '''Auto-generated class.
    '''</remarks>
    Partial Public Class WindowsSignin

        '''<summary>
        '''plSetIIS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSetIIS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plNoAuthentication control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plNoAuthentication As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
